name: calorie_check
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  
  # UI components
  intl: ^0.19.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Hive generators
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  
  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/
